#!/bin/bash

# Función para imprimir mensajes en color
print_style() {
    printf "\e[1;34m%s\e[0m\n" "$1"
}

case $1 in
  artisan)
    print_style "Running php artisan..."
    docker exec -i vidrierianinoback php artisan "${@:2}"
    ;;
  composer)
    print_style "Running composer..."
    docker exec -i vidrierianinoback composer "${@:2}"
    ;;
  npm)
    print_style "Running npm in frontend..."
    docker exec -i vidrierianinofront npm "${@:2}"
    ;;
  test)
    print_style "Running tests..."
    docker exec -i vidrierianinoback php artisan test
    ;;
  migrate)
    print_style "Fresh migration and seed..."
    docker exec -i vidrierianinoback php artisan migrate:fresh --seed
    ;;
  *)
    echo "Uso: ./dev {artisan|composer|npm|test|migrate}"
    echo "Ejemplo: ./dev artisan make:controller MaterialController"
    ;;
esac